alpo/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^quotes/', include('quotes.urls', namespace='quotes')),
    # Examples:
    # url(r'^$', 'alpo.views.home', name='home'),
    # url(r'^alpo/', include('alpo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

quotes/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView

from quotes.models import Quote

from quotes.views import QuoteCreate, QuoteUpdate, QuoteDelete

urlpatterns = patterns('',
        # ex: quotes/
        url(r'^$',
            ListView.as_view(
                queryset=Quote.objects.order_by('-submission_time')[:4],
                context_object_name='latest_quote_list',
                template_name='quotes/index.html'),
            name='index'),
        # ex: /quotes/2/
        url(r'^(?P<pk>\d+)/$',
            DetailView.as_view(
                model=Quote,
                template_name='quotes/detail.html'),
            name='detail'),
        #ex: /quotes/add/
        url(r'^add/$', QuoteCreate.as_view(
                template_name='quotes/form.html'),
            name='create'),
        #ex: /quotes/2/edit/
        url(r'^(?P<pk>\d+)/edit/$', QuoteUpdate.as_view(
                template_name='quotes/form.html'),
            name='update'),
        #ex: /quotes/2/delete/
        url(r'^(?P<pk>\d+)/delete/$', QuoteDelete.as_view(
                template_name='quotes/confirm_delete.html'),
            name='delete'),
)

quotes/models.py
from django.core.urlresolvers import reverse
from django.db import models

class Quote(models.Model):
    message = models.TextField()
    name = models.CharField(max_length=100)
    PROGRAM_CHOICES = (
            ('BCS', 'BTech'),
            ('MCS', 'MTech'),
            ('MCA', 'MCA'),
    )
    program = models.CharField(max_length=3,
                               choices = PROGRAM_CHOICES,
                               default = 'BCS')
    class_of = models.IntegerField("Enter year of passing out")
    submission_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('quotes:detail', kwargs={'pk': self.pk})

quotes/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from quotes.models import Quote

class QuoteCreate(CreateView):
    model = Quote

class QuoteUpdate(UpdateView):
    model = Quote

class QuoteDelete(DeleteView):
    model = Quote
    success_url = reverse_lazy('quotes:index')

quotes/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Untitled{% endblock %} | Alpo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{{STATIC_URL}}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="{{STATIC_URL}}js/bootstrap.min.js" type="text/javascript"></script>
    {% block extrahead %}
    {% endblock %}
    <script type="text/javascript">
    $(function(){
    {% block jquery %}
    {% endblock %}
    });
    </script>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Alpo</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/quotes">Remember</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="messages">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{message.tags}}">
            <a class="close" data-dismiss="alert">×</a>
            {{message}}
          </div>
        {% endfor %}
      {% endif %}
    </div>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div> <!-- /container -->
  </body>
</html>

quotes/templates/quotes/confirm_delete.html
{% extends "base.html" %}

{% block title %}Confirm quote delete{% endblock %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    Are you sure you want to delete?
    <p><input type="submit" value="Yes" /></p>
    <p><a href={% url 'quotes:index' %}>No</a></p>
</form>
{% endblock %}

quotes/templates/quotes/detail.html
{% extends "base.html" %}

{% block title %}Quote by {{ quote.name }}{% endblock %}

{% block content %}
<h1>Quote {{ quote.id }} </h1>
<q>{{ quote.message}}
<span class="author">- {{ quote.name }}, {{ quote.get_program_display }} {{ quote.class_of }}</span></q>

<p><a href={% url 'quotes:update' quote.id %}>Edit</a> | <a href={% url 'quotes:delete' quote.id %}>Delete</a> | <a href={% url 'quotes:index' %}>List all</a></p>
{% endblock %}

quotes/templates/quotes/form.html
{% extends "base.html" %}

{% block title %}Add/edit a quote{% endblock %}

{% block content %}
<form method="POST" action="">{% csrf_token %}
    {{ form }}
    <p><button type="submit">Submit</button></p>
</form>
{% endblock %}

quotes/templates/quotes/index.html
{% extends "base.html" %}

{% block title %}Quotes{% endblock %}

{% block content %}
{% if latest_quote_list %}
    <ul>
    {% for quote in latest_quote_list %}
    <li><a href="{% url 'quotes:detail' quote.id %}">{{ quote.message }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No quotes available.</p>
{% endif %}

<a href={% url 'quotes:create'  %}>Add a quote</a>
{% endblock %}